//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDEXValidator.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class TestSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestSettings defaultInstance = ((TestSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestSettings())));
        
        public static TestSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0""?>
<ernm:NewReleaseMessage xmlns:ddexc=""http://ddex.net/xml/20110630/ddexC"" xmlns:ernm=""http://ddex.net/xml/ern/34"" xmlns:xs=""http://www.w3.org/2001/XMLSchema-instance"" xs:schemaLocation=""http://ddex.net/xml/2011/ern-main/33 http://ddex.net/xml/2011/ern-main/33/ern-main.xsd"" MessageSchemaVersionId=""2011/ern-main/33"" LanguageAndScriptCode=""en"">
	<MessageHeader>
		<MessageThreadId>058AF4F5-4B2B-4fb4-A677-D360350D5013</MessageThreadId>
		<MessageId>058AF4F5-4B2B-4fb4-A677-D360350D5013</MessageId>
		<MessageFileName>AudioSingle.xml</MessageFileName>
		<MessageSender>
			<PartyId>PADPIDA0000000001A</PartyId>
			<TradingName>Iron Crown Music</TradingName>
		</MessageSender>
		<MessageRecipient>
			<PartyId>PADPIDA0000000002A</PartyId>
			<TradingName>Lamson Digital Distribution</TradingName>
		</MessageRecipient>
		<MessageCreatedDateTime>2010-07-23T00:00:00</MessageCreatedDateTime>
		<MessageControlType>TestMessage</MessageControlType>
	</MessageHeader>
</ernm:NewReleaseMessage>")]
        public string EmptyXml {
            get {
                return ((string)(this["EmptyXml"]));
            }
            set {
                this["EmptyXml"] = value;
            }
        }
    }
}
